Added support for Linux arm64
getgauge/gauge_screenshot pull request #4
Opened 2021-07-03 15:01 UTC by xemle

I am playing with gauge on Raspberry PI 4 (linux-arm64) and receive errors due the usage of the screenshot plugin.

Disabling it on the `default.properties` via

```
screenshot_enabled = false
```

did help. And I think why not supporting linux-arm64?

2021-07-04 08:43 UTC, xemle commented
See also PR [gauge #2036](https://github.com/getgauge/gauge/pull/2036)

2021-07-05 03:12 UTC, sriv requested changes
This will also need changes to [`getArch`](https://github.com/getgauge/gauge_screenshot/blob/13b284009bb1e25f719c4beb179371c48c52d0a1/build/make.go#L344)

See https://github.com/getgauge/gauge/pull/1998/files#diff-8dee26221394440174ffc668d5d7e415416a3ceb38f4fa31c8c953792de9e2a9R445 for reference.

2021-07-05 19:08 UTC, xemle commented
I hope my change matches your request. If not, let me know and I will change it.

2021-07-06 02:59 UTC, sriv approved these changes

2021-07-06 03:02 UTC, sriv commented
Could you please bump the version here as well? `0.1.0` seems reasonable.

https://github.com/getgauge/gauge_screenshot/blob/master/version/version.go#L21

2021-07-06 03:11 UTC, merged

2021-07-06 15:46 UTC, xemle commented
Awesome. Thank you very much

2021-07-12 19:21 UTC, xemle commented
Thank you for releasing arm64 version! At least gauge is not crashing on arm64 ;-)

I tried gauge_screenshot 0.1.0 on Raspberry PI 4 running Ubuntu 21.04 but got following error

```
$ ~/.gauge/plugins/screenshot/0.1.0/gauge_screenshot /tmp/foo.png
panic: BadMatch {NiceName: Match, Sequence: 1, BadValue: 310, MinorOpcode: 0, MajorOpcode: 73}

goroutine 1 [running]:
main.main()
	/Users/runner/work/gauge_screenshot/gauge_screenshot/main.go:44 +0x214
```

No idea about that.

It is not that important to me getting this plugin working. If it is a minor issue, I can offer to help somehow...

2021-07-15 01:47 UTC, sriv commented
This is strange, but I do not have access to a linux/arm64 machine, so I cannot investigate this at the moment. I'll try to see if I can source once somehow and will investigate this. 

Could you please open a new issue for this, so that we don't forget it?.

2021-07-15 05:12 UTC, xemle commented
May I donate a Raspberry Pi 4 to you? It is a nice toy and every tech geek should have one ;-) The setup with Ubuntu or Rasperry Pi OS is straight forward.

If you are interested, write a private message.

2021-07-15 06:51 UTC, sriv commented
Thank you for the offer! I am familiar with the Pis and have deployed them for various tasks. I just don't have one that I can spare for this test.

Although, it just occurred to me that I do have an apple silicon macbook, which I should be able to run an Ubuntu VM on. Will give that a shot

2021-07-15 07:14 UTC, xemle commented
I would be happy to give some support via a new playground Pi. Do not hesitate to accept this offer.

If you prefer the VM, it is also fine ;-)

Keep in mind thay I do not rely on the screenshot plugin yet. Maybe shift the investigation when it needed. Just wanted to give feedback about the error.

For me the current setup works out of the box with arm64 for gauge and html-report. I am fine.

2024-02-02 16:03 UTC, sumitmistry23 commented
> Thank you for releasing arm64 version! At least gauge is not crashing on arm64 ;-)
> 
> I tried gauge_screenshot 0.1.0 on Raspberry PI 4 running Ubuntu 21.04 but got following error
> 
> ```
> $ ~/.gauge/plugins/screenshot/0.1.0/gauge_screenshot /tmp/foo.png
> panic: BadMatch {NiceName: Match, Sequence: 1, BadValue: 310, MinorOpcode: 0, MajorOpcode: 73}
> 
> goroutine 1 [running]:
> main.main()
> 	/Users/runner/work/gauge_screenshot/gauge_screenshot/main.go:44 +0x214
> ```
> 
> No idea about that.
> 
> It is not that important to me getting this plugin working. If it is a minor issue, I can offer to help somehow...

I am getting this same issue as well on my ubuntu 22.04.3 amd64 vm. Have you figured out a solution for this ?